import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

export type SprayRecordProduct = {
  product: string;
  reg: string;
  accepted: string;
  restrictedUse: boolean;
};

export type SprayRecordClause = {
  kind: "FIELD CHECK" | "ADVISORY";
  product: string;
  page: string;
  quote: string;
};

export type SprayRecordInput = {
  fieldName: string;
  lat: number;
  lon: number;
  windowStart: string;
  windowEnd: string;
  source: "LIVE" | "RECORDED";
  forecastFetchedAt: string;
  weather: {
    temperature: string;
    wind: string;
    rainChance: string;
    sunAltitude: string;
  };
  products: SprayRecordProduct[];
  clauses: SprayRecordClause[];
};

/*
Historical 7 CFR 110.3(a), effective through July 10, 2025, required:
(1) The brand or product name, and the EPA registration number of the restricted use pesticide that was applied;
(2) The total amount of the restricted use pesticide applied;
(3) The location of the application, the size of area treated, and the crop, commodity, stored product, or site to which a restricted use pesticide was applied.
(4) The month, day, and year on which the restricted use pesticide application occurred; and
(5) The name and certification number (if applicable) of the certified applicator who applied or who supervised the application of the restricted use pesticide.
Historical 7 CFR 110.3(c) stated: The information required in this section shall be recorded within 14 days following the pesticide application.
USDA removed 7 CFR part 110 effective July 11, 2025, at 90 FR 20083. The generated PDF labels this as a former federal checklist and directs the user to current applicable requirements.
*/

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER = "Planning record generated by Labelhand. The label is the law and the applicator decides.";

function localDateTime(value: string): string {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "America/New_York",
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZoneName: "short",
  }).format(new Date(value));
}

function utcDateTime(value: string): string {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "UTC",
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    timeZoneName: "short",
  }).format(new Date(value));
}

function wrapText(text: string, font: PDFFont, size: number, width: number): string[] {
  const paragraphs = text.split("\n");
  const lines: string[] = [];
  for (const paragraph of paragraphs) {
    if (!paragraph) {
      lines.push("");
      continue;
    }
    const words = paragraph.split(/\s+/u);
    let current = "";
    for (const word of words) {
      const candidate = current ? `${current} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) <= width || !current) {
        current = candidate;
      } else {
        lines.push(current);
        current = word;
      }
    }
    if (current) lines.push(current);
  }
  return lines;
}

export async function buildSprayRecordPdf(input: SprayRecordInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`Labelhand spray record for ${input.fieldName}`);
  pdf.setSubject("Application planning record with label clauses and former 7 CFR 110.3 checklist fields");
  pdf.setCreator("Labelhand");
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  let page: PDFPage;
  let y: number;

  function addPage() {
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;
  }

  function ensureSpace(height: number) {
    if (y - height < 56) addPage();
  }

  function drawLines(text: string, options: {
    font?: PDFFont;
    size?: number;
    color?: ReturnType<typeof rgb>;
    indent?: number;
    gapAfter?: number;
  } = {}) {
    const font = options.font ?? regular;
    const size = options.size ?? 10;
    const indent = options.indent ?? 0;
    const lineHeight = size * 1.35;
    const lines = wrapText(text, font, size, CONTENT_WIDTH - indent);
    ensureSpace(lines.length * lineHeight + (options.gapAfter ?? 4));
    for (const line of lines) {
      page.drawText(line, {
        x: MARGIN + indent,
        y,
        size,
        font,
        color: options.color ?? rgb(20 / 255, 33 / 255, 61 / 255),
      });
      y -= lineHeight;
    }
    y -= options.gapAfter ?? 4;
  }

  function heading(text: string) {
    ensureSpace(34);
    y -= 4;
    page.drawRectangle({
      x: MARGIN,
      y: y - 6,
      width: CONTENT_WIDTH,
      height: 24,
      color: rgb(159 / 255, 211 / 255, 242 / 255),
    });
    page.drawText(text, { x: MARGIN + 8, y, size: 13, font: bold, color: rgb(20 / 255, 33 / 255, 61 / 255) });
    y -= 32;
  }

  function blank(label: string) {
    drawLines(`${label}: ______________________________________________________________`, { size: 10, gapAfter: 6 });
  }

  addPage();
  drawLines("LABELHAND SPRAY RECORD", { font: bold, size: 22, gapAfter: 6 });
  drawLines("Prefilled from a forecast-permitted planning window. Complete actual application details in the field.", { size: 10, gapAfter: 12 });

  heading("Field and planned window");
  drawLines(`Field: ${input.fieldName}`);
  drawLines(`Coordinates: ${input.lat.toFixed(6)}, ${input.lon.toFixed(6)}`);
  drawLines(`Planned window: ${localDateTime(input.windowStart)} to ${localDateTime(input.windowEnd)} (America/New_York)`, { gapAfter: 10 });

  heading("Tank products");
  for (const product of input.products) {
    drawLines(`${product.product} | EPA Reg. ${product.reg} | Label accepted ${product.accepted} | Restricted use on this accepted label: ${product.restrictedUse ? "YES" : "NO"}`, { font: bold, gapAfter: 2 });
    blank(`Total amount of ${product.product} applied`);
  }

  heading("Forecast at window start");
  drawLines(`Forecast source: ${input.source}. Forecast fetched ${utcDateTime(input.forecastFetchedAt)}.`);
  drawLines(`Temperature: ${input.weather.temperature} | Wind: ${input.weather.wind} | Rain chance: ${input.weather.rainChance} | Sun altitude: ${input.weather.sunAltitude}`, { gapAfter: 10 });

  heading("Label clauses in this window");
  if (input.clauses.length === 0) {
    drawLines("No FIELD CHECK or advisory clause was attached to an hour in this forecast-permitted window.", { gapAfter: 10 });
  } else {
    for (const clause of input.clauses) {
      drawLines(`${clause.kind} | ${clause.product} | Page ${clause.page}`, { font: bold, gapAfter: 2 });
      drawLines(`"${clause.quote}"`, { indent: 12, gapAfter: 8 });
    }
  }

  heading("Application details to complete");
  blank("Applicator name");
  blank("Applicator certification number, if applicable");
  blank("Crop, commodity, stored product, or site");
  blank("Acres treated");
  blank("Actual application date");
  blank("Actual start time");
  blank("Actual end time");
  blank("Wind measured at the boom");

  heading("Record timing and status");
  drawLines("Former 7 CFR 110.3(c), removed effective July 11, 2025, stated: \"The information required in this section shall be recorded within 14 days following the pesticide application.\"", { font: bold });
  drawLines("7 CFR part 110 is no longer in the current eCFR. Use this as a planning record and follow current state and other applicable recordkeeping requirements.", { gapAfter: 10 });

  for (const outputPage of pdf.getPages()) {
    outputPage.drawLine({
      start: { x: MARGIN, y: 42 },
      end: { x: PAGE_WIDTH - MARGIN, y: 42 },
      thickness: 1,
      color: rgb(20 / 255, 33 / 255, 61 / 255),
    });
    const footerLines = wrapText(FOOTER, regular, 8, CONTENT_WIDTH);
    footerLines.forEach((line, index) => {
      outputPage.drawText(line, { x: MARGIN, y: 28 - index * 9, size: 8, font: regular });
    });
  }

  return pdf.save({ useObjectStreams: false });
}

export async function downloadSprayRecord(input: SprayRecordInput): Promise<void> {
  const bytes = await buildSprayRecordPdf(input);
  const copy = new Uint8Array(bytes);
  const blob = new Blob([copy], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const start = new Date(input.windowStart).toISOString().replace(/[:]/gu, "").slice(0, 13);
  link.href = url;
  link.download = `labelhand-spray-record-${start}.pdf`;
  link.click();
  URL.revokeObjectURL(url);
}
